brew:
  enable_update: false
  enable_upgrade: false
  install_packages:
    - caskroom/cask/brew-cask
    - ctags
    - git
    - jq
    - node
    - rbenv
    - ruby-build
    - vim
  install_apps:
    - google-japanese-ime
    - iterm2
