brew:
  enable_update: false
  enable_upgrade: false
  install_packages:
    - bash
    - ctags
    - dnvm
    - git
    - graphviz
    - imagemagick
    - jq
    - memcached
    - mysql
    - node
    - peco
    - postgresql
    - rbenv
    - redis
    - ruby-build
    - the_silver_searcher
    - ttyrec
    - vim
  install_apps:
    - bettertouchtool
    - caffeine
    - clipmenu
    - cyberduck
    - eclipse-platform
    - google-chrome
    - google-japanese-ime
    - imageoptim
    - iterm2
    - java6
    - java7
    - keycastr
    - kindle
    - licecap
    - skitch
    - sequel-pro
    - caskroom/versions/sublime-text3
    - virtualbox
    - visual-studio-code
    - vagrant
