brew:
  enable_update: false
  enable_upgrade: false
  add_repositories:
    - aspnet/dnx
  install_packages:
    - bash
    - caskroom/cask/brew-cask
    - ctags
    - dnvm
    - git
    - graphviz
    - imagemagick
    - jq
    - memcached
    - mongodb
    - mysql
    - node
    - peco
    - postgresql
    - rbenv
    - redis
    - ruby-build
    - the_silver_searcher
    - ttyrec
    - vim
  install_apps:
    - astah-community
    - bettertouchtool
    - caffeine
    - clipmenu
    - cyberduck
    - eclipse-platform
    - google-chrome
    - google-japanese-ime
    - imageoptim
    - iterm2
    - java
    - keycastr
    - kindle
    - kobito
    - licecap
    - skitch
    - sequel-pro
    - caskroom/versions/sublime-text3
    - virtualbox
    - visual-studio-code
    - vagrant
