brew:
  enable_update: false
  enable_upgrade: false
  install_packages:
    - bash
    - caskroom/cask/brew-cask
    - ctags
    - git
    - jq
    - node
    - peco
    - rbenv
    - ruby-build
    - vim
  install_apps:
    - bettertouchtool
    - caffeine
    - clipmenu
    - cyberduck
    - google-chrome
    - google-japanese-ime
    - imageoptim
    - iterm2
    - caskroom/versions/sublime-text3
    - virtualbox
    - vagrant
